default_language_version:
    python: python3
repos:
-   repo: https://github.com/PyCQA/flake8.git
    rev: 3.7.9  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-print]
        args: ['--enable=T', '--max-line-length=120', '--select=E,W,F', '--ignore=W503']
        exclude: __init__.py
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: debug-statements
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.8.0
    hooks:
    -   id: eslint
        additional_dependencies:
            -   babel-eslint@8.2.6
            -   eslint@4.19.1
            -   prettier@2.0.4
