# Generated by Django 5.0.4 on 2024-09-08 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(editable=False, max_length=300)),
                ('traduction', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.dictionary')),
            ],
        ),
        migrations.AddField(
            model_name='dictionary',
            name='source_language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_dictionaries', to='dictionary.languages'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='target_language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_dictionaries', to='dictionary.languages'),
        ),
    ]
