# Generated by Django 5.0.4 on 2024-11-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_rename_source_language_id_dictionary_source_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='name',
            new_name='original_name',
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('original_name', 'translation')},
        ),
        migrations.AddField(
            model_name='entry',
            name='dictionaries',
            field=models.ManyToManyField(blank=True, related_name='entries', to='dictionary.dictionary'),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='dictionary',
        ),
    ]
